Repository vscode-icons/vscode-icons, pull requests merged in 2018-06, with the labels that each got.

#1603 Improve AppVeyor config
  .appveyor.yml
Labels: devops

#1607 Support Jenkins via language Id
  src/icon-manifest/languages.ts
  src/icon-manifest/supportedExtensions.ts
  src/models/language/languageCollection.ts
Labels: file icons

#1609 Remove bithound config file
  .bithoundrc
Labels: devops

#1617 Move mocha options to an options file
  package.json
  test/mocha.opts
Labels: devops

#1621 Fix babelrc extension
  src/icon-manifest/supportedExtensions.ts
Labels: file icons

#1622 Add better support for Django
  src/icon-manifest/languages.ts
  src/icon-manifest/supportedExtensions.ts
  src/models/language/languageCollection.ts
Labels: file icons

#1624 Add code-climate config file
  .appveyor.yml
  .codeclimate.yml
  .travis.yml
  .vscodeignore
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: devops

#1625 Update dependencies
  package-lock.json
  package.json
  src/commands/index.ts
  src/i18n/languageResourceManager.ts
  src/index.ts
  src/init/projectAutoDetection.ts
  src/init/welcome.ts
  src/models/i18n/index.ts
  src/models/i18n/languageResourceManager.ts
  test/i18n/i18n.test.ts
  test/init/projectAutoDetection.test.ts
  yarn.lock
Labels: greenkeeper

#1626 Get docker trigger script from docker repo
  .travis.yml
  docker/trigger-docker-vsi.sh
Labels: devops

#1629 Disable before_script step in docker stages
  .travis.yml
Labels: devops

#1630 Associate 'plist' with config icon
  src/icon-manifest/supportedExtensions.ts
Labels: file icons
